"""8k streaming

Revision ID: 79ed5390789b
Revises: c6ed73f016ba
Create Date: 2026-04-14 00:19:26.277290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ed5390789b'
down_revision = 'c6ed73f016ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filing_briefing',
    sa.Column('filing_id', sa.String(length=36), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=True),
    sa.Column('bullets', sa.JSON(), nullable=True),
    sa.Column('company_context', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('filing_briefing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filing_briefing_filing_id'), ['filing_id'], unique=True)

    op.create_table('filing_exhibit',
    sa.Column('filing_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('filing_exhibit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filing_exhibit_filing_id'), ['filing_id'], unique=False)

    op.create_table('filing_item',
    sa.Column('filing_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('filing_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filing_item_filing_id'), ['filing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_filing_item_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_filing_item_tier'), ['tier'], unique=False)

    op.create_table('filing_notification',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('filing_id', sa.String(length=36), nullable=False),
    sa.Column('matched_via_watchlist_id', sa.String(length=36), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filing.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_via_watchlist_id'], ['watchlist.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'filing_id', name='uq_notification_user_filing')
    )
    with op.batch_alter_table('filing_notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filing_notification_filing_id'), ['filing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_filing_notification_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notification_user_read', ['user_id', 'read_at'], unique=False)

    with op.batch_alter_table('filing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edgar_entry_id', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('cik', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ticker', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('exchange', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('top_tier', sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column('updated_at_iso', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('is_processed', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_filing_cik'), ['cik'], unique=False)
        batch_op.create_index(batch_op.f('ix_filing_edgar_entry_id'), ['edgar_entry_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_filing_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_filing_top_tier'), ['top_tier'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filing_top_tier'))
        batch_op.drop_index(batch_op.f('ix_filing_ticker'))
        batch_op.drop_index(batch_op.f('ix_filing_edgar_entry_id'))
        batch_op.drop_index(batch_op.f('ix_filing_cik'))
        batch_op.drop_column('is_processed')
        batch_op.drop_column('updated_at_iso')
        batch_op.drop_column('top_tier')
        batch_op.drop_column('title')
        batch_op.drop_column('exchange')
        batch_op.drop_column('ticker')
        batch_op.drop_column('cik')
        batch_op.drop_column('edgar_entry_id')

    with op.batch_alter_table('filing_notification', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_user_read')
        batch_op.drop_index(batch_op.f('ix_filing_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_filing_notification_filing_id'))

    op.drop_table('filing_notification')
    with op.batch_alter_table('filing_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filing_item_tier'))
        batch_op.drop_index(batch_op.f('ix_filing_item_number'))
        batch_op.drop_index(batch_op.f('ix_filing_item_filing_id'))

    op.drop_table('filing_item')
    with op.batch_alter_table('filing_exhibit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filing_exhibit_filing_id'))

    op.drop_table('filing_exhibit')
    with op.batch_alter_table('filing_briefing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filing_briefing_filing_id'))

    op.drop_table('filing_briefing')
    # ### end Alembic commands ###
