"""apply email schema

Revision ID: c6ed73f016ba
Revises: eb65956bd1e3
Create Date: 2026-04-13 19:10:10.248619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ed73f016ba'
down_revision = 'eb65956bd1e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_token',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_token', schema=None) as batch_op:
        batch_op.create_index('ix_auth_token_hash_purpose', ['token_hash', 'purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_token_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_token_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_token_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('auth_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_token_token_hash'))
        batch_op.drop_index(batch_op.f('ix_auth_token_purpose'))
        batch_op.drop_index('ix_auth_token_hash_purpose')

    op.drop_table('auth_token')
    # ### end Alembic commands ###
