"""remove unique constraint on company cik

Revision ID: eb65956bd1e3
Revises: 747c5d017a02
Create Date: 2026-04-09 17:03:39.309259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb65956bd1e3'
down_revision = '747c5d017a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_cik'))
        batch_op.create_index(batch_op.f('ix_company_cik'), ['cik'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_cik'))
        batch_op.create_index(batch_op.f('ix_company_cik'), ['cik'], unique=1)

    # ### end Alembic commands ###
