"""initial schema

Revision ID: 900e9c669a72
Revises: 
Create Date: 2026-05-25 20:30:45.993718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900e9c669a72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('sic', sa.String(length=10), nullable=True),
    sa.Column('state_of_incorporation', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_cik'), ['cik'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_ticker'), ['ticker'], unique=True)

    op.create_table('user',
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=100), nullable=True),
    sa.Column('email_verified', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_google_id'), ['google_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_phone_number'), ['phone_number'], unique=True)

    op.create_table('auth_token',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_token', schema=None) as batch_op:
        batch_op.create_index('ix_auth_token_hash_purpose', ['token_hash', 'purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_token_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_token_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_token_user_id'), ['user_id'], unique=False)

    op.create_table('filing',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('form_type', sa.String(length=20), nullable=False),
    sa.Column('filing_date', sa.String(length=20), nullable=True),
    sa.Column('period_of_report', sa.String(length=20), nullable=True),
    sa.Column('accession_number', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('filing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filing_accession_number'), ['accession_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_filing_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_filing_form_type'), ['form_type'], unique=False)

    op.create_table('filing_event',
    sa.Column('edgar_id', sa.String(length=500), nullable=False),
    sa.Column('signal_type', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('cik', sa.String(length=20), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('company_name', sa.String(length=500), nullable=False),
    sa.Column('filing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edgar_url', sa.String(length=500), nullable=True),
    sa.Column('accession_number', sa.String(length=50), nullable=True),
    sa.Column('max_tier', sa.Integer(), nullable=False),
    sa.Column('items_json', sa.JSON(), nullable=True),
    sa.Column('exhibits_json', sa.JSON(), nullable=True),
    sa.Column('briefing_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('filing_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filing_event_accession_number'), ['accession_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_filing_event_cik'), ['cik'], unique=False)
        batch_op.create_index('ix_filing_event_cik_date', ['cik', 'filing_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_filing_event_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_filing_event_edgar_id'), ['edgar_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_filing_event_filing_date'), ['filing_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_filing_event_max_tier'), ['max_tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_filing_event_signal_type'), ['signal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_filing_event_ticker'), ['ticker'], unique=False)
        batch_op.create_index('ix_filing_event_ticker_date', ['ticker', 'filing_date'], unique=False)

    op.create_table('watchlist',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_user_id'), ['user_id'], unique=False)

    op.create_table('watchlist_companies',
    sa.Column('watchlist_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.id'], ),
    sa.PrimaryKeyConstraint('watchlist_id', 'company_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_companies')
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_user_id'))

    op.drop_table('watchlist')
    with op.batch_alter_table('filing_event', schema=None) as batch_op:
        batch_op.drop_index('ix_filing_event_ticker_date')
        batch_op.drop_index(batch_op.f('ix_filing_event_ticker'))
        batch_op.drop_index(batch_op.f('ix_filing_event_signal_type'))
        batch_op.drop_index(batch_op.f('ix_filing_event_max_tier'))
        batch_op.drop_index(batch_op.f('ix_filing_event_filing_date'))
        batch_op.drop_index(batch_op.f('ix_filing_event_edgar_id'))
        batch_op.drop_index(batch_op.f('ix_filing_event_company_id'))
        batch_op.drop_index('ix_filing_event_cik_date')
        batch_op.drop_index(batch_op.f('ix_filing_event_cik'))
        batch_op.drop_index(batch_op.f('ix_filing_event_accession_number'))

    op.drop_table('filing_event')
    with op.batch_alter_table('filing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filing_form_type'))
        batch_op.drop_index(batch_op.f('ix_filing_company_id'))
        batch_op.drop_index(batch_op.f('ix_filing_accession_number'))

    op.drop_table('filing')
    with op.batch_alter_table('auth_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_token_token_hash'))
        batch_op.drop_index(batch_op.f('ix_auth_token_purpose'))
        batch_op.drop_index('ix_auth_token_hash_purpose')

    op.drop_table('auth_token')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone_number'))
        batch_op.drop_index(batch_op.f('ix_user_google_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_ticker'))
        batch_op.drop_index(batch_op.f('ix_company_cik'))

    op.drop_table('company')
    # ### end Alembic commands ###
