"""Add catalyst table

Revision ID: e25db7d1dccb
Revises: b2c3d4e5f6a7
Create Date: 2026-06-02 09:20:52.032609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e25db7d1dccb'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalyst',
    sa.Column('filing_event_id', sa.String(length=36), nullable=False),
    sa.Column('event_description', sa.String(length=500), nullable=False),
    sa.Column('catalyst_date', sa.Date(), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('company_name', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filing_event_id'], ['filing_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalyst', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalyst_catalyst_date'), ['catalyst_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalyst_filing_event_id'), ['filing_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalyst_ticker'), ['ticker'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalyst', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalyst_ticker'))
        batch_op.drop_index(batch_op.f('ix_catalyst_filing_event_id'))
        batch_op.drop_index(batch_op.f('ix_catalyst_catalyst_date'))

    op.drop_table('catalyst')
    # ### end Alembic commands ###
